config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  authenticated :user do
    root 'categories#index', as: :root 
    resources :categories, only: [:show, :new, :create] do
      resources :transactions, only: [:index, :new, :create, :update, :show, :destory]
    end
  end

  unauthenticated :user do
    root 'splash_screen#home', as: :unauthenticated 
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post, public: true

    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can(:read, Post, user:)

    return unless user.admin? # additional permissions for administrators

    can :read, Post
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :groups, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true

  after_save :total

  def total
    @sum = 0
    entities.each do |e|
      @sum += e.amount
    end
    @sum
  end
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entities, foreign_key: 'author_id'
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:home]
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @group = current_user.groups.order('created_at DESC')
  end

  def show
    @group = current_user.groups.find(params[:id])
    @entities = @group.entities.order('created_at DESC')
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user # assuming you have implemented authentication
    if @group.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def home; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @groups = current_user.groups
    @group = Group.find(params[:category_id])
    @entity = @group.entities.new
  end

  def create
    @group = Group.find(params[:category_id])
    @entity = Entity.new(entity_params.merge(author: current_user))
    if @entity.save
      redirect_to category_path(@group)
    else
      render 'new'
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/views/categories/index.html.erb
<nav class="navbar bg-primary text-center" data-bs-theme="dark">
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'navbar-nav fs-3 text-decoration-none' %>
    <h1 class= "navbar-nav mx-auto">Categories</h1>
</nav>
<main class="container">
    <% @group.each do |item|%>
        <div class="card mb-3 d-flex mx-auto" style="max-width: 540px;">
    <div class="row g-0 align-items-center">
      <div class="col-4 h-100">
        <img src=<%= item.icon%> class="img-fluid rounded-start w-100" alt="...">
      </div>
      <div class="col-8">
        <div class="card-body">
          <h5 class="card-title d-flex justify-content-between">
            <%= link_to item.name, category_path(item.id) %>
            <p>$<%= item.total %></p>
          </h5>
          <p class="card-text"><small class="text-body-secondary"><%= item.created_at%></small></p>
        </div>
      </div>
    </div>
  </div>

    <%end%>
    <div class="text-center">
        <%= link_to "new category", new_category_path, :method => :delete, class: "btn btn-primary" %>
    </div>
</main>

app/views/categories/new.html.erb
<nav class="navbar bg-primary text-center" data-bs-theme="dark">
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'navbar-nav fs-3 text-decoration-none' %>
    <h1 class= "navbar-nav mx-auto">new Categories</h1>
    <%= link_to ">", root_path, :method => :delete, class: 'navbar-nav fs-1 text-decoration-none' %>
</nav>
<%= form_with(model: @group, url: categories_path, class: "my-3") do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :icon, class: "form-label" %>
    <%= form.text_field :icon, class: "form-control" %>
  </div>

  <div class="d-grid gap-2">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<nav class="navbar bg-primary text-center" data-bs-theme="dark">
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'navbar-nav fs-3 text-decoration-none' %>
    <h1 class= "navbar-nav mx-auto">Category</h1>
    <%= link_to ">", root_path, :method => :delete, class: 'navbar-nav fs-1 text-decoration-none' %>
</nav>
<main class="container">
    <div class="row align-items-center" style="max-height: 200px;">
    <div class="col">
        <img src = <%= @group.icon%> alt = 'icon'style="max-height: 200px;">
    </div>
    <div class="col">
        <h2><%= @group.name %></h2>
        <p><%= @group.created_at%></p>
    </div>
    <div class="col">
        <p>$<%= @group.total %></p>
    </div>
    </div>
    <%= link_to "add Transaction", new_category_transaction_path(@group.id), class: "btn btn-primary" %>
    <% @entities.each do |entity|%>
        <div class="row text-center p-4">
        <div class="col">
            <h2><%= entity.name %></h2>
        </div>
        <div class="col">
            <p>$<%= entity.amount %></p>
        </div>
        </div>
    <%end%>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/splash_screen/home.html.erb
<main class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
  <div class="card w-50 p-5" style="margin-top: -10%;">
    <div class="card-body text-center">
      <h1 class="card-title mb-4">Budget</h1>

      <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary w-100 my-2" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-secondary w-100" %>
    </div>
  </div>
</main>

app/views/transactions/new.html.erb
<nav class="navbar bg-primary text-center" data-bs-theme="dark">
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'navbar-nav fs-3 text-decoration-none' %>
    <h1 class= "navbar-nav mx-auto">New transaction</h1>
    <%= link_to ">", category_path(@group), :method => :delete, class: 'navbar-nav fs-1 text-decoration-none' %>
</nav>

<%= form_with(model: @entity, url: category_transactions_path(@group), class: "my-3") do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :group_id, class: "form-label" %>
    <%= form.collection_select :group_id, @groups, :id, :name, { class: "form-select" }, { value: @group.id } %>
  </div>

  <div class="d-grid gap-2">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>